# mkdir -p "${HOME}/workspaces" "${HOME}/.openhands"

name: openhands

services:
  agent-canvas:
    image: ghcr.io/openhands/agent-canvas:1.5.2
    container_name: agent-canvas
    stdin_open: true
    tty: true
    environment:
      TEST: "bbb"
    ports:
      - "8600:8000"
    volumes:
      - "${HOME}/.openhands:/home/openhands/.openhands"
      - "${HOME}/workspaces:/workspaces"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
