services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.18
    container_name: openhands
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.18-nikolaik
      - LOG_ALL_EVENTS=true
    ports:
      - "127.0.0.1:6300:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - openhands-state:/.openhands-state
    restart: unless-stopped
    networks:
      - internal
      - web

volumes:
  openhands-state:

networks:
  internal:
    name: internal
  web:
    name: web
