services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai:latest
    container_name: invokeai
    environment:
      - INVOKEAI_ROOT=~/invokeai
      - HUGGING_FACE_HUB_TOKEN=
      # cuda, rocm
      - GPU_DRIVER=cuda
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    networks:
      - internal
      - web

volumes:
  invokeai:

networks:
  internal:
    name: internal
  web:
    name: web
