version: "3.8"

services:
  caddy:
    image: caddy-security:2.7.6
    # image: caddy:2.7.6-alpine
    container_name: caddy
    restart: unless-stopped
    # command: caddy reverse-proxy --from https://yourdns:443 --to http://wg-easy:51821
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        echo "[+] Creating Caddyfile"
        tee Caddyfile <<EOF
          {
            order authenticate before respond
            order authorize before reverse_proxy
            
            security {
              local identity store localdb {
                realm local
                
                path /etc/caddy/auth/local/users.json
              }
          
              authentication portal myportal {
                enable identity store localdb
                cookie domain zzzzzz.duckdns.org
                cookie lifetime 86400

                transform user {
                  match email zuzuzu@zzzzzz.duckdns.org
                  action add role authp/user
                }
              }

              authorization policy admin_policy {
                allow roles authp/user
              }
            }
          }
        
          zzzzzz.duckdns.org:443 {
            
            route /* {
              respond "root" 200
            }
            
            route /auth* {
              authenticate with myportal
            }
            
            route /hi* {
              respond "hi" 200
            }
            
            route /hey* {
              authorize with admin_policy

              respond "hey" 200
            }
            
            route /portainer* {
              authorize with admin_policy
              uri strip_prefix /portainer

              reverse_proxy portainer:9000
            }

          }
        EOF
        
        echo "[+] Running Caddy"
        caddy run
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ~/.caddy:/data
    networks:
      - web
    environment:
      AUTHP_ADMIN_USER: zuzuzu
      AUTHP_ADMIN_EMAIL: zuzuzu@zzzzzz.duckdns.org
      AUTHP_ADMIN_SECRET: zpzpzp

networks:
  web:
    name: web
    external: true