version: "3.8"

services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:10
    container_name: cobalt
    init: true
    ports:
      - 9000:9000/tcp
      # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
      #- 127.0.0.1:9000:9000
    environment:
      # replace https://api.cobalt.tools/ with your instance's target url in same format
      API_URL: "https://api.cobalt.tools/"
      # if you want to use cookies when fetching data from services, uncomment the next line and the lines under volume
      # COOKIE_PATH: "/cookies.json"
      # see docs/run-an-instance.md for more information
    restart: unless-stopped
    networks:
      - web
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

    # if you want to use cookies when fetching data from services, uncomment volumes and next line
    #volumes:
    #- ./cookies.json:/cookies.json

  # update the cobalt image automatically with watchtower
  # watchtower:
  #     image: ghcr.io/containrrr/watchtower
  #     restart: unless-stopped
  #     command: --cleanup --scope cobalt --interval 900 --include-restarting
  #     volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    name: web
    external: true
