services:
  debian:
    image: debian:12.8
    container_name: debian
    tty: true
    stdin_open: true
    command: /bin/bash
    # ports:
    #   - 8080:8080
    # volumes:
    #   - ~/ubuntu_data:/data
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
  web:
    name: web
