services:
  discount-bandit:
    image: cybrarist/discount-bandit:v3.3
    container_name: discount-bandit
    environment:
      DB_CONNECTION: sqlite
      NTFY_CHANNEL_ID: "shopping"
      NTFY_BASE_URL: "${NTFY_BASE_URL}"
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHANNEL_ID: ""
      DEFAULT_USER: "${USER}"
      DEFAULT_EMAIL: "${EMAIL}"
      DEFAULT_PASSWORD: "${PASSWORD}"
      APP_TIMEZONE: UTC
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      DISABLE_AUTH: 1
      THEME_COLOR: Stone
      APP_URL: "${APP_BASE_URL}/discount"
    ports:
      - "127.0.0.1:6680:80"
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
    external: true
  web:
    name: web
    external: true
