version: "3.8"

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - SUBDOMAINS=zzz
      - TOKEN=zzz
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    name: internal
    external: true
