services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:latest
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ACCOUNT_TOKEN=
      - MACHINE_NAME=
      - CLI_ARGS= #optional
    ports:
      - 7396:7396 #optional
    volumes:
      - /home/ubuntu/fah_config:/config
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
  web:
    name: web
