version: "3.8"

services:
  # TODO: Should be deployed on subdomain
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    # user: "1001:1001"
    stdin_open: true
    tty: true
    # command: >
    #   create-userdir 
    #   --userdir user_data
    # command: >
    #   new-config 
    #   --config user_data/config.json
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
    ports:
      - "8787:8080"
      # - "127.0.0.1:8787:8080"
    volumes:
    # TODO: Make sure directory freqtrade_data exists
      - "./freqtrade_data:/freqtrade/user_data"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
