services:
  glances:
    image: nicolargo/glances:4.2.1
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "127.0.0.1:61208:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
