services:
  glances:
    image: nicolargo/glances:4.2.1
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /mnt/wd1tb:/srv/wd1tb:ro
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
