services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        echo "[+] Creating settings.yaml"
        tee /app/config/settings.yaml <<EOF
          title: mstream Homepage
          # headerStyle: boxed
          headerStyle: boxedWidgets
          cardBlur: sm
          
          showStats: true

          providers:
            - finnhub: ${FINNHUB_API_KEY}
            - openweathermap: ${OWM_API_KEY}

        EOF

        echo "[+] Creating widgets.yaml"
        tee /app/config/widgets.yaml <<EOF
          - datetime:
            text_size: md
            format:
              dateStyle: short
              timeStyle: short
              hour12: true
          
          - resources:
              label: System
              cpu: true
              memory: true
              uptime: true
          - resources:
              label: Storage
              disk: /
          - resources:
              label: Network
              network: true
          
          - search:
              provider: [duckduckgo] # google, duckduckgo, bing, baidu, brave or custom
              focus: true
              showSearchSuggestions: true
              target: _blank
          
          # - openweathermap:
          #     units: metric # or imperial
          #     provider: openweathermap
          #     apiKey: ${OWM_API_KEY}
          #     cache: 5
          
          # - resources:
          #     cpu: true
          #     memory: true
          #     disk: /
          #     cputemp: true
          #     uptime: true
          #     units: metric
          #     refresh: 3000
          #     network: true
          
          # - glances:
          #     url: http://glances:61208
          #     version: 4
          #     cpu: true
          #     mem: true
          #     cputemp: true
          #     uptime: true
          #     disk: /
          #     expanded: true

          # - stocks:
          #     provider: finnhub
          #     apiKey: ${FINNHUB_API_KEY}
          #     watchlist:
          #       - MSFT
          #       - AAPL
          #       - GOOG
          #       - NVDA
        EOF

        echo "[+] Creating services.yaml"
        tee /app/config/services.yaml <<EOF
          - Info:
            - Info:
                href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: info
                  refreshInterval: 5000
            - CPU:
                href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: cpu
                  refreshInterval: 5000
            - Memory:
                href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: memory
                  refreshInterval: 5000
            - Containers:
                # href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: containers
                  refreshInterval: 5000
            - Portainer:
                href: http://${DOMAIN}/portainer
                widget:
                  type: portainer
                  url: https://portainer:9443
                  env: 2
                  key: ${PORTAINER_TOKEN}
            - Caddy:
                widget:
                  type: caddy
                  url: http://caddy-internal:2020
            - Test:
                showStats: true
          - Media:
            - Jellyfin:
                href: http://${DOMAIN}/jellyfin
                widget:
                  type: jellyfin
                  url: http://jellyfin:8096
                  key: ${JELLYFIN_API_KEY}
                  enableBlocks: true # optional, defaults to false
                  enableNowPlaying: true # optional, defaults to true
                  enableUser: true # optional, defaults to false
                  showEpisodeNumber: true # optional, defaults to false
                  expandOneStreamToTwoRows: false # optional, defaults to true
            - Radarr:
                href: http://${DOMAIN}/radarr
                widget:
                  type: radarr
                  url: http://radarr:7878
                  key: ${RADARR_API_KEY}
                  enableQueue: true
            - Sonarr:
                href: http://${DOMAIN}/sonarr
                widget:
                  type: sonarr
                  url: http://sonarr:8989
                  key: ${SONARR_API_KEY}
                  enableQueue: true
            - Prowlarr:
                href: http://${DOMAIN}/prowlarr
                widget:
                  type: prowlarr
                  url: http://prowlarr:9696
                  key: ${PROWLARR_API_KEY}
            - Deluge:
                href: http://${DOMAIN}/deluge
                widget:
                  type: deluge
                  url: http://deluge:8112
                  password: ${DELUGE_PASSWORD}
            - Jellyseerr:
                href: http://${DOMAIN}/jellyseerr
                widget:
                  type: jellyseerr
                  url: http://jellyseerr:5055
                  key: ${JELLYSEERR_API_KEY}
            - Bazarr:
                href: http://${DOMAIN}/bazarr
                widget:
                  type: bazarr
                  url: http://bazarr:6767/bazarr
                  key: ${BAZARR_API_KEY}
          
          - Main:
            - Calendar:
                widget:
                  type: calendar
                  view: monthly
                  showTime: true
                  timezone: Asia/Kolkata
            - Crypto:
                widget:
                  # type: coinmarketcap
                  # currency: USD
                  # symbols: [BTC, ETH]
                  # key: ${CMC_API_KEY}
                  # defaultinterval: 1d
        EOF
        
        echo "[+] Running Homepage"
        node server.js
    environment:
      - OWM_API_KEY=${OWM_API_KEY}
      - DOMAIN=${DOMAIN}
      - PORTAINER_TOKEN=$PORTAINER_TOKEN{}
    ports:
      - "127.0.0.1:8088:3000"
    volumes:
      - ~/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
    external: true
  web:
    name: web
    external: true
