# Host on subdomain, Below Caddy Config:
# hass.$DOMAIN:443 {
#   route /* {
#     authorize with admin_policy
#     reverse_proxy hass:8123
#   }
# }

services:
  init-hass-config:
    image: busybox
    container_name: init-hass-config
    # command: sh -c "mkdir -p /config && touch /config/configuration.yml"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "[+] Creating hass config"

        mkdir -p /config

        tee /config/configuration.yaml <<EOF
          default_config:

          # config if using reverse proxy
          http:
            use_x_forwarded_for: true
            trusted_proxies:
              - 172.19.0.0/16
          
          homeassistant:
            name: viz_hass
            latitude: 32.87336
            longitude: -117.22743
            elevation: 430
            unit_system: metric
            currency: USD
            temperature_unit: C
            time_zone: America/Los_Angeles
            external_url: https://zzzzzz.duckdns.org
            internal_url: http://hass:8123
            allowlist_external_dirs:
              - /config
            allowlist_external_urls:
              - https://fonts.googleapis.com
              - https://fonts.gstatic.com
              - https://cdn.materialdesignicons.com
            media_dirs:
              media: /media
            legacy_templates: false
        EOF

        echo "[+] Created hass config"

        pwd
        ls -all
        ls -all /config
        tree /config

        cat /config/configuration.yaml
    volumes:
      - ./hass_config:/config
    networks:
      - web
    restart: "no"

  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:2025.5"
    container_name: hass
    ports:
      - "8123:8123"
    volumes:
      - ./hass_config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - init-hass-config
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
