services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        set -x
        pwd
        ls -all

        echo "[+] Creating settings.yaml"
        tee /app/config/settings.yaml <<EOF
          title: Viz Homepage
          headerStyle: boxedWidgets
          showStats: true

          providers:
            # openweathermap: ${OWM_API_KEY}
            - openweathermap:
                label: Home
                latitude: 38.98
                longitude: -76.15
                units: imperial
                provider: openweathermap
                apikey: ${OWM_API_KEY}
                cache: 5

        EOF

        echo "[+] Creating widgets.yaml"
        tee /app/config/widgets.yaml <<EOF
          - datetime:
            text_size: md
            format:
              dateStyle: short
              timeStyle: short
              hour12: true
          - search:
              provider: google # google, duckduckgo, bing, baidu, brave or custom
              focus: true
              showSearchSuggestions: true
              target: _blank
          - openweathermap:
              units: metric # or imperial
              provider: openweathermap
              apiKey: ${OWM_API_KEY}
              cache: 5
              format: # optional, Intl.NumberFormat options
                maximumFractionDigits: 1
          # - resources:
          #     cpu: true
          #     memory: true
          #     disk: /
          #     cputemp: true
          #     uptime: true
          #     units: metric
          #     refresh: 3000
          #     network: true
          
          - resources:
              label: System
              cpu: true
              memory: true
          - resources:
              label: Storage
              disk: /
          - resources:
              label: Network
              network: true
          
          # - glances:
          #     url: http://glances:61208
          #     version: 4
          #     cpu: true
          #     mem: true
          #     cputemp: true
          #     uptime: true
          #     disk: /
          #     expanded: true
        EOF

        echo "[+] Creating services.yaml"
        tee /app/config/services.yaml <<EOF
          - Info:
            - Info:
                href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: info
                  refreshInterval: 5000
            - CPU:
                href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: cpu
                  refreshInterval: 5000
            - Memory:
                href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: memory
                  refreshInterval: 5000
            - Containers:
                # href: https://${DOMAIN}/glances
                widget:
                  type: glances
                  url: http://glances:61208
                  version: 4
                  metric: containers
                  refreshInterval: 5000
            - SvcX:
                # href: http://a/
                showStats: true
          - Dev:
            - SvcB:
                # href: http://a/
                widget:
                  type: calendar
                  view: monthly
                  showTime: true
                  timezone: Asia/Kolkata
          - Main:
            - Portainer:
                href: http://${DOMAIN}/portainer
                widget:
                  type: portainer
                  url: https://portainer:9443
                  env: 3
                  key: ${PORTAINER_TOKEN}
            - Svc1:
                href: http://${DOMAIN}
                widget:
                  type: caddy
                  url: http://caddy-security:2019
        EOF
        
        echo "[+] Running Homepage"
        node server.js
    environment:
      - OWM_API_KEY=${OWM_API_KEY}
      - DOMAIN=${DOMAIN}
      - PORTAINER_TOKEN=$PORTAINER_TOKEN{}
    ports:
      - "127.0.0.1:8088:3000"
    volumes:
      - ~/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
    external: true
  web:
    name: web
    external: true
