version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    # image: jellyfin/jellyfin:10
    container_name: jellyfin
    # user: uid:gid
    dns:
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Optional - alternative address used for autodiscovery
      # - JELLYFIN_PublishedServerUrl=http://zzz.com
    ports:
      - 8096:8096
      - 8920:8920 # optional
      - 7359:7359/udp # optional
      - 1900:1900/udp # optional
    volumes:
      - ./jellyfin_config:/config
      - ./jellyfin_cache:/cache
      - /home/proxnet/movies:/movies
      - /home/proxnet/blackhole:/downloads
      - /data/mnt/tv:/tv:ro
      # - type: bind
      #   source: ./media
      #   target: /media
      # read_only: true
    restart: "unless-stopped"
    networks:
      - web

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Kolkata
      - PORT=5055
      # - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped
    networks:
      - web

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME=  #optional
      - USER=                   #optional
      - PASS=                   #optional
    volumes:
      - ./transmission_config:/config
      - /home/proxnet/blackhole:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
