services:
  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: postgres012post

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    container_name: keycloak
    command: >
      start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password012pass
      # DB_VENDOR: POSTGRES
      # DB_ADDR: postgres
      # DB_DATABASE: keycloak
      # DB_USER: keycloak
      # DB_SCHEMA: public
      # DB_PASSWORD: postgres012post
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    # depends_on:
    #   - postgres

    networks:
      - web

volumes:
  postgres_data:
    driver: local

networks:
  web:
    name: web
