services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
    ports:
      - 7860:7860
    volumes:
      - langflow_data:/app/langflow
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - internal
      - web

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow_postgres:/var/lib/postgresql/data

volumes:
  langflow_data:
  langflow_postgres:

networks:
  internal:
    name: internal
  web:
    name: web
