services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    environment:
      - EULA=TRUE
      - RCON_PASSWORD=
    ports:
      - 25565:25565
    volumes:
      - ~/data/minecraft:/data
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
  web:
    name: web
