version: "3.8"

services:
  npm:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: npm
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx_data:/data
      - ./letsencrypt_config:/etc/letsencrypt
    restart: unless-stopped
