version: "3.8"

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
