# TODO: Deploy at subdomain
# 
# Config Doc - https://docs.ntfy.sh/config/
# Execute command in the ntfy container -
# Create a user and grant permission:
# ntfy user add viz
# ntfy access viz "*" rw
# 
# Create a user with admin role:
# ntfy user add --role=admin viz

services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    container_name: ntfy
    command:
      # - ntfy user add --role=admin phil    # Add admin user
      - serve
    # user: 1000:1000
    stdin_open: true
    tty: true
    environment:
      - TZ=UTC
      - NTFY_BASE_URL=http://zzz.duckdns.org
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT=2G
      - NTFY_ATTACHMENT_FILE_SIZE_LIMIT=500M
      - NTFY_ATTACHMENT_EXPIRY_DURATION=200h
      - NTFY_VISITOR_ATTACHMENT_TOTAL_SIZE_LIMIT=2G
      - NTFY_VISITOR_ATTACHMENT_DAILY_BANDWIDTH_LIMIT=2G
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_ENABLE_LOGIN=true
      - NTFY_BEHIND_PROXY=true
    ports:
      - "127.0.0.1:8780:80"
    volumes:
      - /home/ubuntu/ntfy_data:/var/lib/ntfy
      # - /var/lib/ntfy:/var/lib/ntfy
      # - /etc/ntfy:/etc/ntfy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
