version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.24.1
    container_name: portainer
    ports:
      - 6060:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - internal
      - web

volumes:
  portainer_data: {}

networks:
  internal:
    name: internal
  web:
    name: web
