version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 6060:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  portainer_data:
