version: "3.8"

services:
  # Torrent Downloader
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error
    volumes:
      - ./deluge_config:/config
      - /home/proxnet/blackhole:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: unless-stopped
    networks:
      - web

  # Indexer
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - RUN_OPTS=
      # - AUTO_UPDATE=true
    volumes:
      - ./jackett_config:/config
      - /home/proxnet/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - web

  # Indexer
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - web

  # Movies manager
  # /torznab/all/api for jackett
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr_config:/config
      - /home/proxnet/movies:/movies
      - /home/proxnet/blackhole:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - web

  # Shows manager
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sonarr_config:/config
      - /home/proxnet/movies:/movies
      - /home/proxnet/blackhole:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  # Subtitles manager
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bazarr_config:/config
      - /home/proxnet/movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - web

  # Books
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./readarr_config:/config
      - /home/proxnet/books:/books
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
