version: "3.8"

# to run define K3S_TOKEN, K3S_VERSION is optional, eg:
# K3S_TOKEN=${RANDOM}${RANDOM}${RANDOM} docker-compose up
# K3S_VERSION=v1.30.7-k3s1

services:
  k3s_server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: k3s_server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    ports:
      - 6443:6443 # Kubernetes API Server
      - 80:80 # Ingress controller port 80
      - 443:443 # Ingress controller port 443
    volumes:
      - k3s_server:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - .:/output
    privileged: true
    restart: always
    networks:
      - web

  k3s_agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=${K3S_TOKEN:?err}
    volumes:
      - k3s_agent:/var/lib/rancher/k3s
    privileged: true
    restart: always
    networks:
      - web

  rancher:
    image: rancher/rancher:v2.10.0
    container_name: rancher
    ports:
      - 4480:80
    privileged: true
    restart: unless-stopped
    networks:
      - web

volumes:
  k3s_server: {}
  k3s_agent: {}

networks:
  web:
    name: web
