# mkdir -p ~/my_data/rustfs
name: rustfs

services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    environment:
      - TEST=
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=rust012fs
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - ${HOME}/my_data/rustfs:/data
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
    # external: true
  web:
    name: web
    # external: true
