# TODO: Create ~/syncthing_config, ~/syncthing_data, ~/Sync directory

services:
  syncthing:
    image: syncthing/syncthing:1.28.1
    # image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    # entrypoint: ["/bin/sh","-c"]
    # command:
    #   - |
    #     echo "[+] Setting User and Password"
    #     syncthing generate --gui-user=${USER} --gui-password=${SYNCTHING_PASSWORD}
    #     echo "[+] Starting Syncthing"
    #     syncthing serve
    environment:
      - PUID=1000
      - PGID=1000
      - STNODEFAULTFOLDER=1
      - STNOUPGRADE=1
    ports:
      - "127.0.0.1:8384:8384" # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - /home/ubuntu/syncthing_config:/config
      - /home/ubuntu/syncthing_data:/var/syncthing
      - /home/ubuntu/Sync:/sync
    restart: unless-stopped
    networks:
      - web
    # healthcheck:
    #   test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3

networks:
  web:
    name: web
