version: "3.8"

services:
  syncthing:
    image: syncthing/syncthing
    # image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./syncthing_config:/config
      - ./sync_data:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - web
    # healthcheck:
    #   test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3

networks:
  web:
    name: web
