# TODO: mkdir -p /home/ubuntu/data/wireguard/config

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=zzzzzz.duckdns.org #optional
      - SERVERPORT=55555 #optional
      # - SERVERPORT=51820 #optional
      - PEERS=zzz1,zzz2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /home/ubuntu/data/wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 55555:51820/udp
      # - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  internal:
    name: internal
    external: true
  web:
    name: web
    external: true
