kind: Service
apiVersion: v1
metadata:
  name: helidonfirst
  labels:
    app: helidonfirst
spec:
  type: NodePort
  selector:
    app: helidonfirst
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidonfirst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidonfirst
  template:
    metadata:
      labels:
        app: helidonfirst
        version: v1
    spec:
      containers:
      - name: helidonfirst
        image: helidonfirst
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
