@API_ENDPOINT = http://localhost:5043

GET {{API_ENDPOINT}}/weatherforecast/
Accept: application/json

###


GET {{API_ENDPOINT}}/api/v1/projects
Accept: application/json

###



POST {{API_ENDPOINT}}/api/v1/projects
Content-Type: application/json

{
  "name": "ProjectOne"
}

###
